### ISSUE TITLE
manque l'attribut Total dans le resultat

### ISSUE THREAD

**Issue by dahman7** [ntlm-technologies/ntlm.Lydie.Catalog.Doc#1]
1- lancer un recherche : https://test-catalog-lydie.ntlm.tech/search?text=ducato&model=4893&size=10&page=1
## Attendu : 
attribut total est present
attibut size different de 0
attribut page different de 0
## Constaté : 
attribut total est absent
attibut size egale a  0
attribut page egale a  0

**Comment by MamboJoel** [comment]
On a rajouté les éléments de pagination : 

![image](https://user-images.githubusercontent.com/3832009/144382259-8a0fc509-1115-4173-8827-cb5bef3c8ee1.png)
