### ISSUE TITLE
Nombre de resultat SIze

### ISSUE THREAD

**Issue by dahman7** [ntlm-technologies/ntlm.Lydie.Catalog.Doc#2]
1.  lancer la recherche : https://test-catalog-lydie.ntlm.tech/search?text=ducato&model=1889&size=1&page=1
## Constaté
Le nombre de resultat est doublé
## Attendu
Resultat non doublé

**Comment by MamboJoel** [comment]
Je ne reproduis pas. Peut-être que ce problème a été réglé avec la résolution de #1.
Je te laisse vérifier et le cas échéant clore cette issue.
